#!/usr/bin/env bash
#
# usage: bin/compile <build-dir> <cache-dir> <env-dir>
# See https://devcenter.heroku.com/articles/buildpack-api#bin-compile
#

set -eo pipefail
set -x

export GOFLAGS="-v -a -toolexec $GOBIN/sqreen-instrumentation-tool"